require("ddkatch.tweaks.disable-terminal-autoclose")
require("ddkatch.tweaks.json")
require("ddkatch.tweaks.automatic-trailing-whitespace")
require("ddkatch.tweaks.load-env-vars")
require("ddkatch.tweaks.languages")
